### ISSUE TITLE
Replacement Discussion

### ISSUE THREAD

**Issue by sandstrom** [airbnb/stemcell#92]
It seems like AirBnB doesn't use stemcell internally anymore.

It would be interesting to learn what other solution you've switched to (internal or some other open-source mechanism?).

Since this repo is somewhat stalled now, perhaps you could also add a note about this in the readme, explaining in which cases stemcell is still useful, and when people may want to look elsewhere (and at what).

What do you think @darnaut?

**Comment by sandstrom** [comment]
This [paragraph from your engineering blog](https://medium.com/airbnb-engineering/making-breakfast-chef-at-airbnb-8e74efff4707):

> ”Stemcell is currently being internally deprecated in favor of a service which handles the launching of instances. This is because we would like to keep instance launching more consistent and reliable, and also to minimize the number of people in our team with credentials to launch instances.”
> — AirBnB Engineering blog

But perhaps you've reversed course since that was written?

**Comment by darnaut** [comment]
No, that's accurate, but said service uses stemcell. Engineers no longer have to manually use stemcell.

**Comment by sandstrom** [comment]
@darnaut Got it, thanks for clarifying!
