### ISSUE TITLE
Fix running under Chef 14.x

### ISSUE THREAD

**Issue by sandstrom** [airbnb/stemcell#95]
I haven't been able to get Chef running under 14.x, due to the following error:

```
Errno::ENOENT: No such file or directory @ rb_sysopen - /.chef/chef_guid
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/client.rb:1012:in `initialize'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/client.rb:1012:in `open'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/client.rb:1012:in `generate_guid'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/client.rb:262:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/application.rb:279:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/application.rb:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/application/solo.rb:304:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/lib/chef/application/solo.rb:227:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.1.1/bin/chef-solo:25:in `<top (required)>'
/usr/bin/chef-solo:71:in `load'
/usr/bin/chef-solo:71:in `<main>'
```

Everything runs just fine under 13.x. Reading through the [14.x breaking changes](https://docs.chef.io/release_notes.html#breaking-changes) there isn't anything that immediately pops out. 

*There were issues with 13.x too, but I managed to solve (https://github.com/airbnb/stemcell/pull/94) that.*

**Comment by sandstrom** [comment]
@darnaut Hi Davi! Which version of Chef are you running internally?

I've been trying to solve this issue, but haven't found a way forward.

**Comment by sandstrom** [comment]
Hey @vvassiliouk @darnaut 😄 

Just curious to hear if things are working under 14.x for you internally?

**Comment by sandstrom** [comment]
friendly ping! 😄 @darnaut @ljharb @noggi

**Comment by darnaut** [comment]
You might want to consult the Chef source code, https://github.com/chef/chef/blob/master/lib/chef/client.rb#L1005 looks like missing `:chef_guid_path` config option, which is based on https://github.com/chef/chef/blob/master/chef-config/lib/chef-config/config.rb#L738

**Comment by sandstrom** [comment]
@darnaut Thanks for replying! I did dig into `:chef_guid_path` earlier, but couldn't figure out why that error surfaced under 14.x.

After some more digging I did find a solution, please have a look: https://github.com/airbnb/stemcell/pull/100

*(also, for the record, this issue still exist, but the aforementioned PR has a fix for it)*
